[package]
name = "hyperbus"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
clap = "4.5.49"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
tokio-util = "0.7.16"
tracing = "0.1.41"
